import Head from "next/head";
import styles from "../../styles/Home.module.css";
import https from "https";

import { useRouter } from "next/dist/client/router";
import Link from "next/link";
const agent = new https.Agent({
  rejectUnauthorized: false,
});

const defaultEndpoint = "https://rickandmortyapi.com/api/character/";

export async function getServerSideProps({ query }) {
  const { id } = query;

  const res = await fetch(`${defaultEndpoint}/${id}`, { agent } as RequestInit);

  const data = await res.json();
  return {
    props: {
      data,
    },
  };
}

export default function Character({ data }) {
  const { asPath } = useRouter();
  const notHomePage = asPath !== "/";

  const { name, image, gender, location, origin, species, status } = data;

  return (
    <div className={styles.container}>
      <Head>
        <title>{name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.profile}>
        <div className="profile-image">
          <img src={image} alt={name} />
        </div>
        <div className="profile-details">
          <h2>Character-Details</h2>
          <ul>
            <li>
              <strong>Name</strong>
              {name}
            </li>
            <li>
              <strong>Status</strong>
              {status}
            </li>
            <li>
              <strong>Gender</strong>
              {gender}
            </li>
            <li>
              <strong>Species</strong>
              {species}
            </li>
            <li>
              <strong>Location</strong>
              {location?.name}
            </li>
            <li>
              <strong>Originally</strong>
              {origin?.name}
            </li>
          </ul>
        </div>
      </div>
      {notHomePage && (
        <Link href="/">
          <a>
            <strong>Back to all Characteres</strong>
          </a>
        </Link>
      )}
      <main className={styles.main}>
        <h1 className={styles.title}>Wubba Lubba Dub Dub</h1>
      </main>
    </div>
  );
}
