import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import React, { useEffect } from "react";
import https from "https";
import Link from "next/link";
import { useState } from "react";

const agent = new https.Agent({
  rejectUnauthorized: false,
});

const defaultEndpoint = "https://rickandmortyapi.com/api/character/";

export async function getServerSideProps() {
  const res = await fetch(defaultEndpoint, { agent } as RequestInit);

  const data = await res.json();
  return {
    props: {
      data,
    },
  };
}

export default function Home({ data }) {
  const { info, results: defaultResults = [] } = data;
  const [results, updateResults] = useState(defaultResults);

  const [page, updatePage] = useState({
    ...info,
    current: defaultEndpoint,
  });

  const { current } = page;

  useEffect(() => {
    if (current === defaultEndpoint) return;

    async function request() {
      const res = await fetch(current);
      const nextdata = await res.json();

      updatePage({
        current,
        ...nextdata.info,
      });

      if (!nextdata.info?.prev) {
        updateResults(nextdata.results);
        return;
      }

      updateResults((prev) => {
        return [...prev, ...nextdata.results];
      });
    }
    request();
  }, [current]);

  function handleMore() {
    updatePage((prev) => {
      return {
        ...prev,
        current: page?.next,
      };
    });
  }

  function handleOnSubmitSearch(e) {
    e.preventDefault();

    const { currentTarget = {} } = e;
    const fields = Array.from(currentTarget?.elements);
    const fieldQuery = fields.find((field) => field.name === "query");

    const value = fieldQuery.value || "";
    const endpoint = `https://rickandmortyapi.com/api/character/?name=${value}`;

    updatePage({
      current: endpoint,
    });
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Wubba Lubba Dub Dub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Wubba Lubba Dub Dub</h1>

        <p className={styles.description}>Rick and Morty wiki</p>

        <form className={styles.searchInput} onSubmit={handleOnSubmitSearch}>
          <input name="query" type="search" />
          <button>Search</button>
        </form>

        <ul className={styles.grid}>
          {results.map((result) => {
            const { name, id, image } = result;
            return (
              <li key={id} className={styles.card}>
                <Link href={`/characters/${id}`}>
                  <a>
                    <img src={image} alt={name} className={styles.image} />
                    <h2>{name}</h2>
                  </a>
                </Link>
              </li>
            );
          })}
        </ul>
        <p>
          <button onClick={handleMore}>Load more caracteres</button>
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
